/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as BrowserRouteImport } from './routes/browser'
import { Route as CloudRouteImport } from './routes/cloud'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminBrowserRouteImport } from './routes/admin.browser'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminHostnamePoliciesRouteImport } from './routes/admin.hostname-policies'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminLibrariesRouteImport } from './routes/admin.libraries'
import { Route as AdminLibrariesIndexRouteImport } from './routes/admin.libraries.index'
import { Route as AdminLibrariesPublishRouteImport } from './routes/admin.libraries.publish'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserRoute = BrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrowserRoute = AdminBrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHostnamePoliciesRoute = AdminHostnamePoliciesRouteImport.update({
  id: '/hostname-policies',
  path: '/hostname-policies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLibrariesRoute = AdminLibrariesRouteImport.update({
  id: '/libraries',
  path: '/libraries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLibrariesIndexRoute = AdminLibrariesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLibrariesRoute,
} as any)
const AdminLibrariesPublishRoute = AdminLibrariesPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AdminLibrariesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/browser': typeof BrowserRoute
  '/cloud': typeof CloudRoute
  '/documents': typeof DocumentsRoute
  '/jobs': typeof JobsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/browser': typeof AdminBrowserRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/hostname-policies': typeof AdminHostnamePoliciesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/libraries': typeof AdminLibrariesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/libraries/publish': typeof AdminLibrariesPublishRoute
  '/admin/libraries/': typeof AdminLibrariesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/agents': typeof AgentsRoute
  '/browser': typeof BrowserRoute
  '/cloud': typeof CloudRoute
  '/documents': typeof DocumentsRoute
  '/jobs': typeof JobsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/browser': typeof AdminBrowserRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/hostname-policies': typeof AdminHostnamePoliciesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/libraries/publish': typeof AdminLibrariesPublishRoute
  '/admin/libraries': typeof AdminLibrariesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/browser': typeof BrowserRoute
  '/cloud': typeof CloudRoute
  '/documents': typeof DocumentsRoute
  '/jobs': typeof JobsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/browser': typeof AdminBrowserRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/hostname-policies': typeof AdminHostnamePoliciesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/libraries': typeof AdminLibrariesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/libraries/publish': typeof AdminLibrariesPublishRoute
  '/admin/libraries/': typeof AdminLibrariesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/agents'
    | '/browser'
    | '/cloud'
    | '/documents'
    | '/jobs'
    | '/library'
    | '/login'
    | '/logs'
    | '/settings'
    | '/sources'
    | '/admin/audit-logs'
    | '/admin/browser'
    | '/admin/catalog'
    | '/admin/hostname-policies'
    | '/admin/jobs'
    | '/admin/libraries'
    | '/admin/'
    | '/admin/libraries/publish'
    | '/admin/libraries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/agents'
    | '/browser'
    | '/cloud'
    | '/documents'
    | '/jobs'
    | '/library'
    | '/login'
    | '/logs'
    | '/settings'
    | '/sources'
    | '/admin/audit-logs'
    | '/admin/browser'
    | '/admin/catalog'
    | '/admin/hostname-policies'
    | '/admin/jobs'
    | '/admin'
    | '/admin/libraries/publish'
    | '/admin/libraries'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/agents'
    | '/browser'
    | '/cloud'
    | '/documents'
    | '/jobs'
    | '/library'
    | '/login'
    | '/logs'
    | '/settings'
    | '/sources'
    | '/admin/audit-logs'
    | '/admin/browser'
    | '/admin/catalog'
    | '/admin/hostname-policies'
    | '/admin/jobs'
    | '/admin/libraries'
    | '/admin/'
    | '/admin/libraries/publish'
    | '/admin/libraries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentsRoute: typeof AgentsRoute
  BrowserRoute: typeof BrowserRoute
  CloudRoute: typeof CloudRoute
  DocumentsRoute: typeof DocumentsRoute
  JobsRoute: typeof JobsRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser': {
      id: '/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof BrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud': {
      id: '/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/browser': {
      id: '/admin/browser'
      path: '/browser'
      fullPath: '/admin/browser'
      preLoaderRoute: typeof AdminBrowserRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hostname-policies': {
      id: '/admin/hostname-policies'
      path: '/hostname-policies'
      fullPath: '/admin/hostname-policies'
      preLoaderRoute: typeof AdminHostnamePoliciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/libraries': {
      id: '/admin/libraries'
      path: '/libraries'
      fullPath: '/admin/libraries'
      preLoaderRoute: typeof AdminLibrariesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/libraries/': {
      id: '/admin/libraries/'
      path: '/'
      fullPath: '/admin/libraries/'
      preLoaderRoute: typeof AdminLibrariesIndexRouteImport
      parentRoute: typeof AdminLibrariesRoute
    }
    '/admin/libraries/publish': {
      id: '/admin/libraries/publish'
      path: '/publish'
      fullPath: '/admin/libraries/publish'
      preLoaderRoute: typeof AdminLibrariesPublishRouteImport
      parentRoute: typeof AdminLibrariesRoute
    }
  }
}

interface AdminLibrariesRouteChildren {
  AdminLibrariesPublishRoute: typeof AdminLibrariesPublishRoute
  AdminLibrariesIndexRoute: typeof AdminLibrariesIndexRoute
}

const AdminLibrariesRouteChildren: AdminLibrariesRouteChildren = {
  AdminLibrariesPublishRoute: AdminLibrariesPublishRoute,
  AdminLibrariesIndexRoute: AdminLibrariesIndexRoute,
}

const AdminLibrariesRouteWithChildren = AdminLibrariesRoute._addFileChildren(
  AdminLibrariesRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminBrowserRoute: typeof AdminBrowserRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminHostnamePoliciesRoute: typeof AdminHostnamePoliciesRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminLibrariesRoute: typeof AdminLibrariesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminBrowserRoute: AdminBrowserRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminHostnamePoliciesRoute: AdminHostnamePoliciesRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminLibrariesRoute: AdminLibrariesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentsRoute: AgentsRoute,
  BrowserRoute: BrowserRoute,
  CloudRoute: CloudRoute,
  DocumentsRoute: DocumentsRoute,
  JobsRoute: JobsRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
