/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as CloudRouteImport } from './routes/cloud'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SourcesRouteImport } from './routes/sources'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/cloud': typeof CloudRoute
  '/documents': typeof DocumentsRoute
  '/jobs': typeof JobsRoute
  '/library': typeof LibraryRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/cloud': typeof CloudRoute
  '/documents': typeof DocumentsRoute
  '/jobs': typeof JobsRoute
  '/library': typeof LibraryRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/cloud': typeof CloudRoute
  '/documents': typeof DocumentsRoute
  '/jobs': typeof JobsRoute
  '/library': typeof LibraryRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/agents'
    | '/cloud'
    | '/documents'
    | '/jobs'
    | '/library'
    | '/logs'
    | '/settings'
    | '/sources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin'
    | '/agents'
    | '/cloud'
    | '/documents'
    | '/jobs'
    | '/library'
    | '/logs'
    | '/settings'
    | '/sources'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/agents'
    | '/cloud'
    | '/documents'
    | '/jobs'
    | '/library'
    | '/logs'
    | '/settings'
    | '/sources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRoute
  AgentsRoute: typeof AgentsRoute
  CloudRoute: typeof CloudRoute
  DocumentsRoute: typeof DocumentsRoute
  JobsRoute: typeof JobsRoute
  LibraryRoute: typeof LibraryRoute
  LogsRoute: typeof LogsRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud': {
      id: '/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRoute,
  AgentsRoute: AgentsRoute,
  CloudRoute: CloudRoute,
  DocumentsRoute: DocumentsRoute,
  JobsRoute: JobsRoute,
  LibraryRoute: LibraryRoute,
  LogsRoute: LogsRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
